name: Create Release
on:
  create:
    tags:
      - "*"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run
        run: ./build.sh
        shell: bash
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: Arcadia-${{ github.ref }}.zip
          asset_name: Arcadia-${{ github.ref }}.zip
          tag: ${{ github.ref }}
          overwrite: true