name: Update Release
on:
  push:
    tags:
      - "**"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run
        id: create_release
        run: ./build.sh
        shell: bash
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_PAT }}
          file: ./build/Arcadia-${{ github.ref_name }}.zip
          asset_name: Arcadia-${{ github.ref_name }}.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload to Curseforge
        uses: itsmeow/curseforge-upload@3.1.1
        with:
          token: ${{ secrets.CURSEFORGE_TORKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          game_endpoint: wow
          file_path: ./build/Arcadia-${{ github.ref_name }}.zip
