on:
  push:
    branches:
      - canary
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_PAT }}
          release-type: simple
          package-name: Arcadia
          prerelease: true
          include-v-in-tag: true
          default-branch: canary
          version-file: VERSION.txt