on:
  push:
    branches:
      - alpha
      - beta
      - canary
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_PAT }}
          release-type: simple
          package-name: Arcadia
          default-branch: ${{ github.ref }}
          prerelease: ${{ github.ref_name == 'alpha' || github.ref_name == 'beta' }}
          version-file: VERSION.txt
          pull-request-title-pattern: "v${version}"
          # component: "${{ github.ref_name }}"